<a href="https://colab.research.google.com/github/SumanRoy004/only-for-uploading-colab-file/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [96]:
df=pd.read_csv('/content/iphone_purchase_records.csv')
df.head()

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [97]:
df.shape

(400, 4)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64 
 2   Salary           400 non-null    int64 
 3   Purchase Iphone  400 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


In [99]:
df.describe()

Age         Salary  Purchase Iphone
count  400.000000     400.000000       400.000000
mean    37.655000   69742.500000         0.357500
std     10.482877   34096.960282         0.479864
min     18.000000   15000.000000         0.000000
25%     29.750000   43000.000000         0.000000
50%     37.000000   70000.000000         0.000000
75%     46.000000   88000.000000         1.000000
max     60.000000  150000.000000         1.000000

In [100]:
df['Purchase Iphone'].value_counts(normalize=True)

Purchase Iphone
0    0.6425
1    0.3575
Name: proportion, dtype: float64

In [101]:
# Replacing the 'Male' and 'Female' values by 0 and 1 respectively
df['Gender']=df['Gender'].replace({'Female':1,'Male':0})

In [102]:
df.head()

Gender  Age  Salary  Purchase Iphone
0       0   19   19000                0
1       0   35   20000                0
2       1   26   43000                0
3       1   27   57000                0
4       0   19   76000                0

In [103]:
x=df.iloc[:,0:3].values
y=df.iloc[:,-1].values

In [104]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [105]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [106]:
x_train

array([[-1.04475034,  0.70196731, -1.28920196],
       [ 0.95716648, -0.9554555 , -0.31097586],
       [-1.04475034, -0.9554555 ,  0.28188845],
       [ 0.95716648,  0.01949909,  1.26011455],
       [ 0.95716648,  0.99445369,  2.03083815],
       [ 0.95716648,  1.48193098,  0.3708181 ],
       [-1.04475034, -1.34543734, -0.42954872],
       [ 0.95716648,  0.99445369,  1.46761706],
       [ 0.95716648,  1.38443552, -1.43741804],
       [-1.04475034,  0.21449001,  0.04474273],
       [-1.04475034,  0.21449001,  0.16331559],
       [ 0.95716648, -0.85796004, -0.66669444],
       [ 0.95716648, -0.66296912, -0.04418692],
       [ 0.95716648, -0.27298729, -0.66669444],
       [-1.04475034, -0.17549183,  0.87475276],
       [-1.04475034,  0.01949909, -0.31097586],
       [-1.04475034, -0.85796004,  2.3272703 ],
       [ 0.95716648,  1.77441736,  1.02296883],
       [ 0.95716648,  0.40948093,  0.28188845],
       [ 0.95716648,  2.06690374,  0.40046131],
       [ 0.95716648, -1.05295096, -1.140

In [107]:
# Model Creation
from sklearn.linear_model import LogisticRegression
logit=LogisticRegression()
logit.fit(x_train,y_train)

LogisticRegression()

In [108]:
y_pred=logit.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [109]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [110]:
# Performance Measurement using accuracy and Performance Metrics
from sklearn.metrics import accuracy_score,confusion_matrix
ACC=accuracy_score(y_test,y_pred)
print(ACC)

0.85


In [111]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[49  5]
 [ 7 19]]
